---
bibliography:
- biblio.bib
citation-style: ieee.csl
geometry: "top=3cm, bottom=3cm, left=3cm, right=3cm"
fontsize: 12pt
fontfamily: tgpagella
#fontfamily: times
lang: es-ES
header-includes:
- \usepackage{subfig}
- \usepackage{lscape}
#- \usepackage[ruled,vlined]{algorithm2e}
- \usepackage{fancyhdr}
- \fancyhf{}
- \cfoot{\thepage}
- \pagestyle{fancy}
# - \usepackage{libertine}
# Para incluir fichero separado con código LaTeX
#- \input{separators/preamble.tex}
title: Implementación de una infraestructura REST con privacidad para GTD basada en Express y React Native 
author: Pablo Gamo González, Carlos Gómez López, Javier Gil Caballero, Alejandro Del Río Caballero
advisor: Juan Carlos Sáez Alcaide
department: Departamento de Arquitectura de Computadores y Automática
program: Grado en Ingeniería del Software y Grado en Ingeniería Informática
course: 2023-2024
date: 2024
---