---
bibliography:
- biblio.bib
citation-style: ieee.csl
geometry: "top=3cm, bottom=3cm, left=3cm, right=3cm"
fontsize: 12pt
fontfamily: times
lang: es-ES
header-includes:
- \usepackage{subfig}
#- \usepackage[ruled,vlined]{algorithm2e}
- \usepackage{fancyhdr}
- \fancyhf{}
- \cfoot{\thepage}
- \pagestyle{fancy}
title: Algo relacionado con cambios en PMCTrack
author: Lázaro Clemen Palafox
advisor: Juan Carlos Sáez Alcaide
program: Grado en Ingeniería de Computadores
date: 2021
---